data(iris)
xdata=iris$Sepal.Length
minQ=quantile(xdata,0)
fQ=quantile(xdata,0.25)
sQ=quantile(xdata,0.25)
tQ=quantile(xdata,0.25)
maxQ=quantile(xdata,1)
cat("Minimum=",minQ)
cat("Lower Quartile",fQ)
cat("Median=",sQ)
cat("Upper Quartile",tQ)
cat("MAximum",maxQ)
AQ=quantile(xdata,prob=c(0,0.25,0.5,0.75,1))
cat("All the quantile ",AQ)
summary(xdata)
boxplot(xdata,main="InterQuartile Range for Sepal legth",ylab="centimeters")
as.numeric(quantile(xdata,0.75)-quantile(xdata,0.25))
IQR(xdata)