xdata=c(5,10,12,15,20,25,27,30,29)
MinQ=quantile(xdata,0)
FQ=quantile(xdata,0.25)
SQ=quantile(xdata,0.5)
TQ=quantile(xdata,0.75)
MaxQ=quantile(xdata,1)
cat("Minimum=",MinQ)
cat("Lower Quartile",FQ)
cat("Median=",SQ)
cat("Upper Quartile",TQ)
cat("MAximum",MaxQ)
AQ=quantile(xdata,prob=c(0,0.25,0.5,0.75,1))
cat("All the quantile ",AQ)
summary(xdata)
par(mar = c(2, 2, 2, 2))
#plot(xdata,type="o")
boxplot(xdata,main="InterQuartile RAnge(IQR)",ylab="xdata")
as.numeric(quantile(xdata,0.75)-quantile(xdata,0.25))
IQR(xdata)